-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 21:09:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema brew_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brew_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS brew_project DEFAULT CHARACTER SET utf8;
USE brew_project ;

-- -----------------------------------------------------
-- Table brew_project.images.csv
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.image (
  image_id INT NOT NULL AUTO_INCREMENT,
  image_description VARCHAR(45) NOT NULL,
  image_url VARCHAR(45) NOT NULL,
  PRIMARY KEY (image_id));


-- -----------------------------------------------------
-- Table brew_project.styles
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.style (
  style_id INT NOT NULL AUTO_INCREMENT,
  style_name VARCHAR(45) NOT NULL,
  style_category VARCHAR(45) NOT NULL,
  style_bjcp VARCHAR(5) NOT NULL,
  style_min_ibu INT NOT NULL,
  style_max_ibu INT NOT NULL,
  style_min_abv INT NOT NULL,
  style_max_abv INT NOT NULL,
  style_min_fg FLOAT NOT NULL,
  style_max_fg FLOAT NOT NULL,
  style_min_co2_vol FLOAT NOT NULL,
  style_max_co2_vol FLOAT NOT NULL,
  style_lovibond INT NOT NULL,
  image_id INT,
  PRIMARY KEY (style_id),
  CONSTRAINT image_id
    FOREIGN KEY (image_id)
    REFERENCES brew_project.image (image_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table brew_project.notes
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.notes (
  notes_id INT NOT NULL AUTO_INCREMENT,
  notes_body VARCHAR(255) NOT NULL,
  notes_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (notes_id));


-- -----------------------------------------------------
-- Table brew_project.recipe
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.recipe (
  recipe_id INT NOT NULL AUTO_INCREMENT,
  recipe_name VARCHAR(45) NOT NULL,
  recipe_method VARCHAR(16) NOT NULL,
  recipe_srm INT NOT NULL,
  recipe_batch_size FLOAT NOT NULL,
  recipe_rating INT NOT NULL DEFAULT 0,
  recipe_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  recipe_description VARCHAR(255) NULL,
  style_id INT NOT NULL,
  image_id INT NOT NULL,
  notes_id INT NULL,
  PRIMARY KEY (recipe_id),
  CONSTRAINT r_style_id
    FOREIGN KEY (style_id)
    REFERENCES brew_project.style (style_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT r_image_id
    FOREIGN KEY (image_id)
    REFERENCES brew_project.image (image_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT r_notes_id
    FOREIGN KEY (notes_id)
    REFERENCES brew_project.note (notes_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table brew_project.malt
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.malt (
  malt_id INT NOT NULL AUTO_INCREMENT,
  malt_name VARCHAR(45) NOT NULL,
  malt_origin VARCHAR(16),
  malt_category VARCHAR(16),
  malt_type VARCHAR(16) NOT NULL,
  malt_lovibond INT NOT NULL,
  malt_ppg FLOAT NOT NULL,
  PRIMARY KEY (malt_id));


-- -----------------------------------------------------
-- Table brew_project.hops
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.hops (
  hops_id INT NOT NULL AUTO_INCREMENT,
  hops_variety VARCHAR(45) NOT NULL,
  hops_type VARCHAR(10) NOT NULL,
  hops_aa FLOAT NOT NULL,
  hops_use VARCHAR(10) NOT NULL,
  PRIMARY KEY (hops_id));


-- -----------------------------------------------------
-- Table brew_project.yeast
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.yeast (
  yeast_id INT NOT NULL AUTO_INCREMENT,
  yeast_strain VARCHAR(45) NOT NULL,
  yeast_lab VARCHAR(16) NOT NULL,
  yeast_code VARCHAR(16),
  yeast_type VARCHAR(16) NOT NULL,
  yeast_floc VARCHAR(16) NOT NULL,
  yeast_atten FLOAT NOT NULL,
  yeast_min_temp FLOAT NOT NULL,
  yeast_max_temp FLOAT NOT NULL,
  PRIMARY KEY (yeast_id));


-- -----------------------------------------------------
-- Table brew_project.other
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS brew_project.other (
  other_id INT NOT NULL AUTO_INCREMENT,
  other_name VARCHAR(45) NOT NULL,
  other_type VARCHAR(10) NOT NULL,
  other_use VARCHAR(10) NOT NULL,
  PRIMARY KEY (other_id));


-- -----------------------------------------------------
-- Table brew_project.malt ingredient
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.malt_ingredient (
  malt_id INT NOT NULL,
  recipe_id INT NOT NULL,
  malt_ingred_qty FLOAT NOT NULL,
  PRIMARY KEY (malt_id, recipe_id),
  CONSTRAINT m_malt_id
    FOREIGN KEY (malt_id)
    REFERENCES brew_project.malt (malt_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT m_recipe_id
    FOREIGN KEY (recipe_id)
    REFERENCES brew_project.recipe (recipe_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table brew_project.hops ingredient
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.hops_ingredient (
  hops_id INT NOT NULL,
  recipe_id INT NOT NULL,
  hops_ingred_qty FLOAT NOT NULL,
  hops_time TIME NOT NULL,
  PRIMARY KEY (hops_id, recipe_id),
  CONSTRAINT h_hops_id
    FOREIGN KEY (hops_id)
    REFERENCES brew_project.hops (hops_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT h_recipe_id
    FOREIGN KEY (recipe_id)
    REFERENCES brew_project.recipe (recipe_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table brew_project.yeast_ingredients
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.yeast_ingredient (
  yeast_id INT NOT NULL,
  recipe_id INT NOT NULL,
  yeast_ingred_qty INT NOT NULL,
  yeast_ingred_starter VARCHAR(10) NOT NULL,
  PRIMARY KEY (yeast_id, recipe_id),
  CONSTRAINT y_yeast_id
    FOREIGN KEY (yeast_id)
    REFERENCES brew_project.yeast (yeast_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT y_recipe_id
    FOREIGN KEY (recipe_id)
    REFERENCES brew_project.recipe (recipe_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table brew_project.other_ingredients
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.other_ingredient (
  other_id INT NOT NULL,
  recipe_id INT NOT NULL,
  other_ingred_qty INT NOT NULL,
  PRIMARY KEY (other_id, recipe_id),
  CONSTRAINT o_other_id
    FOREIGN KEY (other_id)
    REFERENCES brew_project.other (other_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT o_recipe_id
    FOREIGN KEY (recipe_id)
    REFERENCES brew_project.recipe (recipe_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table brew_project.session
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.session (
  session_id INT NOT NULL AUTO_INCREMENT,
  session_name VARCHAR(45) NOT NULL,
  session_start TIME NULL,
  session_end TIME NULL,
  session_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  recipe_id INT NULL,
  session_step_id INT NULL,
  PRIMARY KEY (session_id),
  CONSTRAINT s_recipe_id
    FOREIGN KEY (recipe_id)
    REFERENCES brew_project.recipe (recipe_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table brew_project.temps
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.temps (
  temp_id INT NOT NULL AUTO_INCREMENT,
  temp_hlt FLOAT NOT NULL,
  temp_mlt FLOAT NOT NULL,
  temp_bk FLOAT NOT NULL,
  temp_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  session_id INT NOT NULL,
  PRIMARY KEY (temp_id),
  CONSTRAINT session_id
    FOREIGN KEY (session_id)
    REFERENCES brew_project.session (session_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table brew_project.step
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.step (
  step_id INT NOT NULL AUTO_INCREMENT,
  recipe_id INT(11) NOT NULL,
  step_name VARCHAR(16) NOT NULL,
  step_kettle VARCHAR(45) NOT NULL,
  step_temp FLOAT NOT NULL,
  step_timer INT NULL,
  PRIMARY KEY (step_id),
  CONSTRAINT st_recipe_id
    FOREIGN KEY (recipe_id)
    REFERENCES brew_project.recipe (recipe_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table brew_project.session_step
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS brew_project.session_step (
  session_id INT(11) NOT NULL,
  step_id INT NOT NULL,
  session_step_start TIME NOT NULL,
  session_step_end TIME NOT NULL,
  PRIMARY KEY (session_id, step_id),
  CONSTRAINT ss_session_id
    FOREIGN KEY (session_id)
    REFERENCES brew_project.session (session_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ss_step_id
    FOREIGN KEY (step_id)
    REFERENCES brew_project.step (step_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table brew_project.user
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS brew_project.user (
--  username VARCHAR(16) NOT NULL,
--  email VARCHAR(255) NULL,
--  password VARCHAR(32) NOT NULL,
--  create_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
